config/routes.rb
Drwho::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user_registrations", :sessions => "user_sessions" }    
  
  get "inbox", :to => 'inbox#index', :as => :inbox
  get "inbox/:inbox_id", :to => 'inbox#show', :as => :inbox_show
  put "inbox/read/:id", :to => 'inbox#read', :as => :inbox_read
  #delete "inbox/delete/:id", :to => 'inbox#delete'

  get "news/:id", :to => 'news#show', :as => :news_item
  get "news/title/:title", :to => 'news#show_by_title', :as => :news_item_by_title
  get "news", :to => 'news#index', :as => :news_index
  get "my_account", :to => 'my_account#profile', :as => :my_account
  get "my_account/profile"
  get "my_account/cart"
  get "my_account/receipt"
  get "my_account/choose_start_day"
  get "my_account/study_record"
  get "my_account/self_learning"
  get "my_account/news"
  get "my_account/logout"
  get "my_account/calendar", :to => 'my_account#calendar'

  get 'pages/:key', :to => 'pages#show', :as => :page

  get 'profile', :to => 'user_profiles#show', :as => :user_profiles
  get 'profile', :to => 'user_profiles#show', :as => :user_profile
  get 'profile', :to => 'user_profiles#show', :as => :profile
  patch 'profile', :to => 'user_profiles#update'
  get 'profile/edit', :to => 'user_profiles#edit', :as => :edit_user_profile
  

  post 'cart/add/:id(.:format)', :to => 'carts#add', :as => :add_to_cart
  delete 'cart/:id', :to => 'carts#delete', :as => :delete_cart
  get 'cart', :to => 'carts#show', :as => :cart


  get 'order/new/:order_number', :to => 'user_orders#new', :as => :new_user_order
  post 'order/new/:order_number', :to => 'user_orders#new'
  get 'orders', :to => 'user_orders#index', :as => :user_orders
  get 'order/:order_number', :to => 'user_orders#show', :as => :user_order
  resources :user_orders, :only => [:index, :show, :new]
  resources :courses, :only => [:index, :show]

  # SelfLearnings
  get 'study/self_learnings', :to => 'self_learnings#index', :as => :self_learnings
  post 'study/self_learnings', :to => 'self_learnings#create'
  get 'study/self_learning/new', :to => 'self_learnings#new', :as => :self_learning_new
  get 'study/self_learning/:grouping_id', :to => 'self_learnings#show', :as => :self_learning
  patch 'study/self_learning/:grouping_id', :to => 'self_learnings#update'
  delete 'study/self_learning/:grouping_id', :to => 'self_learnings#destroy'
  get 'study/self_learning/:grouping_id/exam', :to => 'self_learnings#exam', :as => :self_learning_exam
  post 'study/self_learning/:grouping_id/exam', :to => 'self_learnings#exam_result'
  get 'study/self_learning/:grouping_id/edit', :to => 'self_learnings#edit', :as => :self_learning_edit


  # Records
  get 'study/records', :to => 'studies#all_records', :as => :study_all_records
  get 'study/records/:uuid', :to => 'studies#record', :as => :study_records  
  get 'study/wrongs/', :to => 'study_records#wrongs', :as => :wrongs
  get 'study/wrongs/course/', :to => 'study_records#wrongs_by_course', :as => :wrongs_by_course
  get 'study/wrongs/course/:uuid', :to => 'study_records#wrongs_in_course', :as => :wrongs_in_course
  get 'study/hardests/:uuid(/course/:course_id)', :to => 'studies#hardests', :as => :study_hardests

  # studies
  get 'study', :to => 'studies#index', :as => :studies
  #    exam
  get 'study/exam/:uuid/day/:day/phase/:phase', :to => 'studies#exam', :as => :study_exam
  post 'study/exam/:uuid/day/:day/phase/:phase', :to => 'studies#exam_submit'
  #    practice
  get 'study/exam/result/:uuid', :to => 'studies#exam_result', :as => :study_exam_result
  get 'study/practice/:uuid/day/:day/phase/:phase', :to => 'studies#practice', :as => :study_practice
  post 'study/practice/:uuid/day/:day/phase/:phase', :to => 'studies#practice_submit'  
  get 'study/practice/result/:uuid', :to => 'studies#practice_result', :as => :study_practice_result
  #    read
  get 'study/read/:uuid/day/:day', :to => 'studies#read', :as => :study_read
  #    set start day
  get "study/set_start_day", :to => 'studies#set_start_day', :as => :set_start_day
  patch 'study/set_start_day/:uuid', :to => 'studies#set_start_day'
  #    show
  get 'study/:uuid', :to => 'studies#show', :as => :study
  



  get 'portal/:id', :to => 'ads#go', :as => :portal
  root :to => 'home#welcome'

end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_profile
  before_filter :select_studies, :only => [:index, :all_records]
  before_filter :select_study, :only => [:show, :record, :read, :practice, :exam, :compare_result]

  def index
    now = Time.now
    @studies = @studies.where('ends_at >= ?', now)
  end

  def show
  end

  def record
    @user = current_user
    @records = @study.study_records.select('course_item_id, count(*) AS cnt, course_id, study_id').group('course_id').order('cnt DESC')
    render 'record_courses'
  end

  def all_records
    @current_section = 'account'
    now = Time.now
    @studies = @studies.where('ends_at <= ?', now)
    render 'record_all'
  end

  def practice
    @day = params[:day]
    @phase = params[:phase].to_i
    @course_items = @study.course.course_items.where('day = ?', @day)
    @type = 'practice'

    @action_target = 'practice_submit'
    case @phase
    when 0
      render 'practice_0'
    when 1
      render 'practice_1'
    when 2
      render 'practice_2'
    else
      render 'practice_0'
    end
  end

  def exam
    @day = params[:day].to_i
    @phase = params[:phase].to_i
    @course_items = @study.course.course_items.where('day = ?', @day)
    @type = 'exam'
    @action_target = 'exam_submit'

    if @phase < 3 #DESC
      @course_items = @study.course.course_items.where('day <= ? AND day > ?', @day,  @day - 10).order('day DESC, id DESC')
    elsif @phase < 6 #ASC
      @course_items = @study.course.course_items.where('day <= ? AND day > ?', @day,  @day - 10).order('day ASC, id ASC')
    elsif @phase < 9 #DESC odd, even
      @course_items = @study.course.course_items.where('day <= ? AND day > ?', @day,  @day - 10).order('day DESC, id DESC').partition {|v| v.id.even? }
      course_items_even = @course_items[0]
      course_items_odd = @course_items[1]
      @course_items = course_items_odd.concat(course_items_even)
    elsif @phase < 12 #DESC even, odd
      @course_items = @study.course.course_items.where('day <= ? AND day > ?', @day,  @day - 10).order('day DESC, id DESC').partition {|v| v.id.even? }
      course_items_even = @course_items[0]
      course_items_odd = @course_items[1]
      @course_items = course_items_even.concat(course_items_odd)
    end
    
    case @phase
    when 0, 3, 6, 9
      render 'practice_0'
    when 1, 4, 7, 10
      render 'practice_1'
    when 2, 5, 8, 11
      render 'practice_2'
    end
  end

  def exam_submit
    @type = 'exam'
    @phase = params[:phase].to_i
    uuid = compare_result(3)

    if uuid
      redirect_to study_exam_result_path(:uuid => uuid)
    else
      flash[:error] = t("errors.messages.duplicate_exam_submit")
      redirect_to study_path(:uuid => params[:uuid])
    end

  end

  def practice_submit
    @type = 'practice'
    @phase = params[:phase].to_i
    uuid = compare_result(2)
    if uuid
      redirect_to study_practice_result_path(:uuid => uuid)
    else
      redirect_to study_path(:uuid => params[:uuid])
    end
  end

  def exam_result
    stage = 3
    get_result(stage)
  end

  def practice_result
    stage = 2
    get_result(stage)
  end

  def read
    @study = current_user.studies.where("uuid = ?", params[:uuid]).first
    @course = @study.course
    @day = params[:day]
    @course_items = @study.course.course_items.where('day = ?', @day)

    if @study.progresses.where('stage = 1 AND day = ?', @day).first.nil?
      @study.progresses.create(
        :user_id => current_user.id,
        :course_id => @study.course_id,
        :day => @day,
        :course_item_id => @study.course.course_items.first.id,
        :stage => 1
      )
    end
  end

  def set_start_day
    if request.patch?
      @study = current_user.studies.where("uuid = ?", params[:uuid]).first
      @study.starts_at = params[:starts_at]
      @study.ends_at = @study.starts_at + @study.course.duration_days - 1

      @study.save if params[:save] == 'true'
      
      render :json => @study
      return

    else
      sort = params[:sort]
      dir = params[:dir]

      case sort
      when 'price'
        sort = 'payment_price'
      when 'order_number', 'id', 'created_at'
      when 'title'
        sort = 'courses.title'
      when 'category'
        sort = 'categories.title'
      else
        sort = 'order_number'
      end
      @current_section = 'account'
      @studies = current_user.studies.where("starts_at > ? OR starts_at IS NULL", Time.now()).joins(:user_order).joins(:course => :category).group("studies.id").order(sort + ' ' + dir).page(params[:page])
      
      if @studies.length == 0
        render "set_start_day_none"
      else
        render "set_start_day"
      end
    end
  end


:private

  def compare_result(stage)
    @study = current_user.studies.where("uuid = ?", params[:uuid]).first
    @day = params[:day]
    @phase = params[:phase].to_i
    save_progress = true

    p = @study.progresses.where(:day => @day, :stage => stage, :phase => @phase).first
    unless p.nil?
      save_progress = false
      puts "WILL NOT SAVE"
      if stage == 3
        return false
      end
    end
    
    user_id = current_user.id
    study_id = @study.id
    course_id = @study.course_id

    course_ids = Array.new
    @results = Hash.new
    
    total_questions = params[:course_items].length.to_i
    total_wrongs = 0.0
    @try = Try.new
    
    Progress.transaction do
      params[:course_items].each do |key, value|
        course_ids.push(key.to_i)
        ci = CourseItem.find(key.to_i)
        #wrong = ci.question.downcase.gsub(/[^0-9a-z]/i, '') != value.downcase.gsub(/[^0-9a-z]/i, '')  ? true : false
        wrong = ci.question != value ? true : false
        value = '__' if value == ''
        
        StudyRecord.create(
          :user_id => user_id,
          :course_item_id => key.to_i,
          :content => value,
          :study_id => study_id,
          :course_id => course_id,
          :wrong => wrong,
          :stage => stage,
          :phase => @phase,
          :try_id => @try.id
        )
        if wrong
          total_wrongs += 1
        end
      end # end of loop

      @score = (1 - total_wrongs / total_questions) * 100

      @try.score = @score.round(2)
      @try.user_id = user_id
      @try.study_id = study_id
      @try.course_id = course_id
      @try.day = @day
      @try.phase = @phase
      @try.stage = stage
      @try.save

      @score = @score.round(0)
      if save_progress
        Progress.create(
          :user_id => current_user.id,
          :course_item_id => 0,
          :study_id => @study.id,
          :course_id => @study.course_id,
          :stage => stage,
          :phase => @phase,
          :day => @day,
          :score => @score
        )
      end
    end # end of transaction
    return @try.id
  end # end of method

  def get_result(stage)
    @try = Try.where(:id => params[:uuid]).first
    if @try.nil?
      redirect_to studies_path
      return
    end

    @study = current_user.studies.where(:id => @try.study_id).first
    @day = @try.day
    @phase = @try.phase
    @stage = @try.stage
    @progress = @study.progresses.where(
      :course_id => @study.course_id,
      :stage => @stage,
      :phase => @phase,
      :day => @day,
    ).order("id ASC").last
    
    @study_records = @try.records.order("id ASC").all
    @score = @try.score.round(0)
  end

  def select_studies
    @current_section = 'studies'
    sort = params[:sort]
    dir = params[:dir]

    case sort
    when 'category'
      sort = 'categories.title'
    when 'title'
      sort = 'courses.title'
    when 'unit'
      sort = 'courses.unit'
    when 'serial'
      sort = 'courses.serial'
    when 'starts_at', 'ends_at'
    else
      sort = 'starts_at'
    end
    
    now = Time.now
    # starts_at: utc date only.
    # now: local time date and time.
    @studies = current_user.studies.where('starts_at <= ?', now).joins(:course).joins(:category).order(sort + ' ' + dir).page(params[:page])
    # DateTime.now.beginning_of_day
    # DateTime.now.end_of_day
    @studies.each do |study|
      end_day = study.ends_at.to_time.end_of_day

      if end_day < now and study.score.blank?
        #caculate the final GPA
        score = caculate_score(study.id)
        study.score = score
        study.passed = score >= 95.00 ? true : false
        Study.find(study.id).update(:score => study.score, :passed => study.passed)
      end
    end
  end

  def caculate_score(study_id)
    score = 0.0
    total_exams = 0
    total_days = Study.find(study_id).course.duration_days
    exams_in_day = Array.new(total_days, 0)
    progresses = current_user.progresses.where(:study_id => study_id, :stage => 3).order("day ASC").all
    progresses.each do |pro|
      exams_in_day[pro.day - 1] = exams_in_day[pro.day - 1] + 1
      score = score + pro.score
      total_exams = total_exams + 1
    end

    exams_in_day.each do |exam|
      total_exams = total_exams + 1 if exam == 0
    end

    score = score / total_exams if total_exams > 0
    return score
  end

  def select_study
    @current_section = 'studies' 
    @ended = false
    @study = current_user.studies.where("uuid = ?", params[:uuid]).first
    #@study = current_user.studies.find(params[:id])
    # stage: 3 => exam
    # phase: start from 0, max 12, the "module"
    # GPA = SUM( SUM(scores_of_day) / module_of_day_taken ) / total_days
    #@story_records = @study.progresses.where('stage = 3').all

    @gpa = 0.0
    #@story_records.each |rec| do
    #end
    if @study.score.nil?
      @gpa = @study.progresses.where('stage = 3').select("AVG(score) AS gpa").first.gpa
    else 
      @gpa = @study.score
    end
  end
    
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_links.html.erb
<%= link_to study_path(@study.uuid), :class => "btn" do %>
  <i class="icon-arrow-left"></i>回到課程進度學習表
<% end %>

app/views/studies/_submit_button.html.erb
<button type="submit" class="btn btn-primary pull-right" ><i class="icon-ok"></i> 送出</button>

app/views/studies/hardest_all.html.erb
<h3>易錯排行榜</h3>
<h4>全部課程易錯排行榜</h4>
<% if @records.length == 0 %>
<p class="alert alert-info">您沒有任何錯誤，真是太棒了！</p>
<% else %>
<table class="table table-striped">
  <tr class="row">
    <th>易錯單字、片語、或例句</th>
    <th class="span2">測驗錯誤次數</th>
    <th class="span2">課程編號</th>
  </tr>
  <% @records.each do |record| %>
  <% study_id = record.study.uuid %>
  <tr class="row">
    <td class=""><%= record.course_item.english %></td>
    <td class="span2"><%= record.cnt %></td>
    <td class="span2"><%= link_to record.course.serial, study_hardests_path(study_id, record.course_id) %></td>
  </tr>
  <% end %>
</table>
<% end %>

app/views/studies/hardest_question.html.erb
<h3>易錯排行榜</h3>
<h4>課程編號 <%= @course.serial %></h4>
<p>
    <%= @course.category.title %> <br>
    <%= @course.title %> <br>
    <%= @course.unit %> <br>
    <%= @course.serial %> <br>
</p>
<% if @records.length == 0 %>
<p class="alert alert-info">您沒有任何錯誤，真是太棒了！</p>
<% else %>

<table class="table table-striped">
  <tr class="row">
    <th>易錯單字、片語、或例句</th>
    <th class="span2">測驗錯誤次數</th>
    
  </tr>
  <% @records.each do |record| %>
  <% study_id = record.study.uuid %>
  <tr class="row">
    <td class=""><%= record.course_item.english %></td>
    <td class="span2"><%= record.cnt %></td>
    
  </tr>
  <% end %>
</table>
<% end %>

<%= link_to :back, :class => "btn" do %>
<i></i> 返回 
<% end %>


<!--
<h1>易錯排行榜</h1>
<h2>單一課程易錯排行榜</h2>

<table class="table table-striped">
  <tr class="row">
    <th class="span2">課程分類</th>
    <th >課程名稱</th>
    <th class="span2">單元數</th>
    <th class="span2">課程編號</th>
    <th class="span2">易錯排行榜</th>
    
  </tr>
  <% @records.each do |record| %>
  <% study_id = record.study_id %>
  <tr class="row">
    <td class=""><%= record.course.category.title %></td>
    <td class=""><%= record.course.title %></td>
    <td class=""><%= record.course.unit %></td>
    <td class=""><%= record.course.serial %></td>

    <td class="span2"><%= link_to '易錯排行榜', '#' %></td>
    
  </tr>
  <% end %>
</table>
-->

app/views/studies/hardest_questions.html.erb
<h1>易錯排行榜</h1>
<h2>全部課程易錯排行榜</h2>

<table class="table table-striped">
  <tr class="row">
    <th>易錯單字、片語、或例句</th>
    <th class="span2">測驗錯誤次數</th>
    <th class="span2">課程編號</th>
  </tr>
  <% @records.each do |record| %>
  <% study_id = record.study.uuid %>
  <tr class="row">
    <td class=""><%= record.course_item.english %></td>
    <td class="span2"><%= record.cnt %></td>
    <td class="span2"><%= link_to record.course.serial, study_hardests_path(study_id, record.course_id) %></td>
  </tr>
  <% end %>
</table>

app/views/studies/read.html.erb
<link rel="stylesheet" href="/assets/study.css">
<script src="/javascripts/audio-player.js"></script>
<h2 class="title title_day">第 <%= @day %> 天的進度 課程內容</h2>
<p>
  當您按下語音檔，按一次開始重複播放，再按一次即停止。建議您先聽全部單字拼音，按一次之後，閉上眼睛專心聆聽。直到聽到單字可以馬上知道如何拼字後，再按一次以停止播放，繼續下方內容的學習。
</p>

<ul>
  <li>步驟一：<a class="btn btn-play" data-audio-url="<%= CourseItem.file_path + @course.serial + "_day" + @day %>"><i class="icon-headphones"></i>播放全部單字拼音</a></li>
  <li>步驟二：
    <div id="audio_player">Loading the player...</div>
    <div id="study_block">
      <% i = 0 %>
      <% @course_items.each do |item| %>
      <% i = i + 1 %>
      <div class="">
	    <dl class="course_item course_item_<%= i %> span10">
	 	 <dt><%= item.question %></dt>
	 	 <dd data-audio-url="<%= item.file_path %>">
	 	   <%= item.answer %>
	 	 </dd>
	    </dl>
	    <a class="btn btn-play pull-right span1" data-audio-url="<%= item.file_path %>"><i class="icon-headphones"></i> 播放</a>
  	  </div>
      <% end %>
    </div>
  </li>
</ul>
<%= link_to study_path(@study.uuid), :class => "btn btn" do %>
  <i class="icon-arrow-left"></i> 完成學習內容，回到課程進度學習表
<% end %>
<%= link_to study_practice_path(:uuid => @study.uuid, :day => params[:day], :phase => 0), :class => "btn btn pull-right" do %>
  完成學習內容，前往練習一 <i class="icon-arrow-right"></i>
<% end %>

app/views/studies/set_start_day.html.erb
<h3>選開課日</h3>
<p>請選擇以下已訂購課程的開課日，請注意，已經開始的課程無法更改開課日</p>
<p class="alert alert-danger start-on-today" style="display:none;">
  您選擇了從今日開始上課，一旦您離開此頁面，將無法更改此課程之開課日
</p>
<div class="order-item">

  <table class="table table-strip">
    <tr class="sortable">   
      <th class="span2 order-number" data-sorting="order-number" >訂購單編號</th>
      <th class="category" data-sorting="category">課程分類</th>
      <th class="title" data-sorting="title">課程名稱</th>
      <th class="unit" data-sorting="unit">單元數</th>
      <th class="span1">上課時間長度</th>
      <th class="span2">開始上課日期</th>
      <th class="span2">結束上課日期</th>
      <th class="span"></th>
    </tr>
    <% @studies.each do |study| %>
    <tr>
      <td><%= study.user_order.order_number %></td>
      <td><%= study.course.category.title %></td>
      <td><%= link_to study.course.title, course_path(study.course_id) %></td>
      <td><%= study.course.unit %></td>
      <td><%= study.course.duration_days %> 天</td>
      <td class="span2">
        <input class="start-day span2" data-duration-days="<%= study.course.duration_days %>" data-id="<%= study.uuid %>" id="study_<%= study.uuid %>_starts_at" min="<%= Date.today %>" name="study[<%= study.uuid %>][starts_at]" type="date" value="<%= study.starts_at %>" />
      <td class="span2">
        <input class="end-day span2" id="study_<%= study.uuid %>_ends_at" name="study[<%= study.uuid %>][ends_at]" readonly="readonly" type="date" value="<%= study.ends_at %>" />
      </td>
      <td><a data-id="<%= study.uuid %>" id="study_<%= study.uuid %>_submit" class="btn btn-primary save" disabled >儲存</a></td>
    </tr>
    <% end %>
  </table>
  <%= paginate @studies %>
</div>

<script type="text/javascript">
var set_start_day_path = "<%= set_start_day_path %>/";
$(document).ready(function(){
  $("input.start-day").change(function(ev){
    id = $(this).data('id');
    day = $(this).val();
    setStartDay(day, id, false);
  });

  $("a.save").click(function(ev){
    id = $(this).data('id');
    day = $("input#study_" + id + "_starts_at").val();

    setStartDay(day, id, true);
  });
  function setStartDay(day, id, save) {
    if (typeof save == undefined) {
      save = false
    } 
    $.ajax({
      url: set_start_day_path + id,
      method: 'patch',
      dataType: 'json',
      data: {starts_at: day, save: save},
      success: function(res){
        var currentDate = new Date()
        var day = currentDate.getDate()
        if (day < 10) { day = '0' + day; }
        var month = currentDate.getMonth() + 1
        if (month < 10) { month = '0' + month; }
        var year = currentDate.getFullYear()
        today = year + "-" + month + "-" + day
        if(res.starts_at == today) {
          $(".start-on-today").slideDown("slow");
        }
        $('#study_' + id + '_ends_at').val(res.ends_at);
        if(save) {
          $('#study_' + id + '_submit').attr('disabled', true);
        } else {
          $('#study_' + id + '_submit').removeAttr('disabled');
        }
      }
    });
  }
});
</script>

app/views/studies/set_start_day_none.html.erb
<h3>選開課日</h3>
<p class="alert alert-information">您沒有尚未開始的課程，前往<%= link_to "上課去", studies_path %>或是<%= link_to "選購課程", courses_path %></p>

app/views/studies/show.html.erb
<h3><%= current_user.fullname %> 課程進度學習表</h3>
<%= render "study_detail_table" %>
<table class="table table-striped table-study">
  <colgroup>
    <col class="light-blue-bg">
    <col class="">
    <col class="light-blue-bg">
    <col class="">
    <col class="light-blue-bg">
    <col class="">
  </colgroup>
  <tr>
    <th>每天<br>進度</th>
    <th>建議<br>完成日期</th>
    <th>進度</th>
    <th>課程<br>內容</th>
    <th>練習<br>
    <span>完成至少一個模組，才能進行測驗</span></th>
    <th>測驗記錄 (GPA = <%= @gpa %>)<br>
    <span>完成至少一個測驗，才能進行下一天的進度</span></th>
  </tr>
  <% for i in 0..@study.course.duration_days - 1 do
    do_link = true
    due_day = @study.starts_at + i
    #due_day = due_day.to_datetime
    last_second = due_day.to_s + ' 23:59:59'
    due_day = DateTime.parse(last_second)
    #puts due_day
    #due_day = due_day.to_s + " 23:59:59"
    today = Date.today
    day = i + 1
    
    progress_behind = false
    progress_ahead = false
    
    link_reading_str = '內容'

    progresses = @study.progresses
    completed_date_reading = progresses.where('stage = 1 AND day = ?', day).first
    completed_date_reading = completed_date_reading.created_at unless completed_date_reading.nil?

    completed_date_practice = progresses.where('stage = 2 AND day = ?', day).first
    completed_date_practice = completed_date_practice.created_at unless completed_date_practice.nil?

    completed_date_exam = progresses.where('stage = 3 AND day = ?', day).first
    completed_date_exam = completed_date_exam.created_at unless completed_date_exam.nil?

    unless completed_date_exam.nil?
      progress_ahead = true if completed_date_exam.to_date < due_day.to_date
      progress_behind = true if completed_date_exam.to_date > due_day.to_date
    else
      progress_behind = true if today > due_day
    end

    link_reading_str = completed_date_reading.localtime.strftime("%-m / %-d") unless completed_date_reading.nil?
    #link_reading_str = completed_date_reading.localtime if !completed_date_reading.nil?


    status_str = '正常'
    status_class = 'normal'
    if progress_behind
      status_str = '落後' 
      status_class = 'behind'
    elsif progress_ahead
      status_str = '超前' 
      status_class = 'ahead'
    end
    practices = progresses.where('stage = 2 AND day = ?', day)
    exams = progresses.where('stage = 3 AND day = ?', day)
    do_link = false if (progresses.where('stage = 3 AND day = ?', day - 1).length == 0 and day > 1)
    
  %>
  <tr class='<%= status_class %>'>
    <td class="day">第<%= day %>天</td>
    <td class="suggested-day"><%= due_day.strftime("%-m / %-d")  %></td>
    <td class="status"><%= status_str %></td>
    <td class="read">
      <% if do_link %>
      <%= link_to link_reading_str, study_read_path(@study.uuid, :day => i + 1) %>
      <% else %>
      <%= link_reading_str %>
      <% end %>
    </td>
    <td class="nopadding practice">
      <table class="practice">
      <tr>
        <% for j in 0..2 %>
        <% do_link = false if j > practices.length || completed_date_reading.nil? %>
        <td>
          <% if do_link %>
          <%= link_to practices[j].nil? ? (j + 1).to_chinese : practices[j].created_at.strftime("%-m / %-d"), study_practice_path(@study.uuid, :day => day, :phase => j) %>
          <% else %>
          <%= (j + 1).to_chinese %>
          <% end %>
        </td>
        <% do_link = true %>
        <% end %>
        
      </tr>
      </table>
    </td>
    <td class="nopadding exam">
      <table>
        <tr>
          <td class="exam-date"><%= exams[0].nil? ? ' - ' : exams[0].created_at.strftime("%-m / %-d") %></td>
          <td class="nopadding">
            <table class="exam">
              <% for k in 0..1 %>
              <% start = k == 0 ? 0 : 6 %>
              <% ending = k == 0 ? 5 : 11 %>
              <tr class="<%= 'alpha' if k == 0 %>">
                <% for j in start..ending %>
                <% index = j %>
                <% do_link = false if j > exams.length || practices.length == 0 || !exams[j].nil? %>
                <td class="exam-result nopadding">
                  <div class="serial">
                    <%= index + 1 %>
                  </div>
                  <div class="score">
                  <% if do_link %>
                    <%= link_to exams[index].nil? ? "測驗" : exams[index].score, study_exam_path(@study.uuid, :day => day, :phase => index) %>
                  <% else %>
                    <%= exams[index].nil? ? '-' : exams[index].score %>
                  <% end %>
                  </div>
                </td>
                <% do_link = true %>
                <% end %>
              </tr>
            <% end %>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <% end %>
</table>