config/routes.rb
Drwho::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user_registrations", :sessions => "user_sessions" }    
  
  get "inbox", :to => 'inbox#index', :as => :inbox
  get "inbox/:inbox_id", :to => 'inbox#show', :as => :inbox_show
  put "inbox/read/:id", :to => 'inbox#read', :as => :inbox_read
  #delete "inbox/delete/:id", :to => 'inbox#delete'

  get "news/:id", :to => 'news#show', :as => :news_item
  get "news/title/:title", :to => 'news#show_by_title', :as => :news_item_by_title
  get "news", :to => 'news#index', :as => :news_index
  get "my_account", :to => 'my_account#profile', :as => :my_account
  get "my_account/profile"
  get "my_account/cart"
  get "my_account/receipt"
  get "my_account/choose_start_day"
  get "my_account/study_record"
  get "my_account/self_learning"
  get "my_account/news"
  get "my_account/logout"
  get "my_account/calendar", :to => 'my_account#calendar'

  get 'pages/:key', :to => 'pages#show', :as => :page

  get 'profile', :to => 'user_profiles#show', :as => :user_profiles
  get 'profile', :to => 'user_profiles#show', :as => :user_profile
  get 'profile', :to => 'user_profiles#show', :as => :profile
  patch 'profile', :to => 'user_profiles#update'
  get 'profile/edit', :to => 'user_profiles#edit', :as => :edit_user_profile
  

  post 'cart/add/:id(.:format)', :to => 'carts#add', :as => :add_to_cart
  delete 'cart/:id', :to => 'carts#delete', :as => :delete_cart
  get 'cart', :to => 'carts#show', :as => :cart


  get 'order/new/:order_number', :to => 'user_orders#new', :as => :new_user_order
  post 'order/new/:order_number', :to => 'user_orders#new'
  get 'orders', :to => 'user_orders#index', :as => :user_orders
  get 'order/:order_number', :to => 'user_orders#show', :as => :user_order
  resources :user_orders, :only => [:index, :show, :new]
  resources :courses, :only => [:index, :show]

  # SelfLearnings
  get 'study/self_learnings', :to => 'self_learnings#index', :as => :self_learnings
  post 'study/self_learnings', :to => 'self_learnings#create'
  get 'study/self_learning/new', :to => 'self_learnings#new', :as => :self_learning_new
  get 'study/self_learning/:grouping_id', :to => 'self_learnings#show', :as => :self_learning
  patch 'study/self_learning/:grouping_id', :to => 'self_learnings#update'
  delete 'study/self_learning/:grouping_id', :to => 'self_learnings#destroy'
  get 'study/self_learning/:grouping_id/exam', :to => 'self_learnings#exam', :as => :self_learning_exam
  post 'study/self_learning/:grouping_id/exam', :to => 'self_learnings#exam_result'
  get 'study/self_learning/:grouping_id/edit', :to => 'self_learnings#edit', :as => :self_learning_edit


  # Records
  get 'study/records', :to => 'studies#all_records', :as => :study_all_records
  get 'study/records/:uuid', :to => 'studies#record', :as => :study_records  
  get 'study/wrongs/', :to => 'study_records#wrongs', :as => :wrongs
  get 'study/wrongs/course/', :to => 'study_records#wrongs_by_course', :as => :wrongs_by_course
  get 'study/wrongs/course/:uuid', :to => 'study_records#wrongs_in_course', :as => :wrongs_in_course
  get 'study/hardests/:uuid(/course/:course_id)', :to => 'studies#hardests', :as => :study_hardests

  # studies
  get 'study', :to => 'studies#index', :as => :studies
  #    exam
  get 'study/exam/:uuid/day/:day/phase/:phase', :to => 'studies#exam', :as => :study_exam
  post 'study/exam/:uuid/day/:day/phase/:phase', :to => 'studies#exam_submit'
  #    practice
  get 'study/exam/result/:uuid', :to => 'studies#exam_result', :as => :study_exam_result
  get 'study/practice/:uuid/day/:day/phase/:phase', :to => 'studies#practice', :as => :study_practice
  post 'study/practice/:uuid/day/:day/phase/:phase', :to => 'studies#practice_submit'  
  get 'study/practice/result/:uuid', :to => 'studies#practice_result', :as => :study_practice_result
  #    read
  get 'study/read/:uuid/day/:day', :to => 'studies#read', :as => :study_read
  #    set start day
  get "study/set_start_day", :to => 'studies#set_start_day', :as => :set_start_day
  patch 'study/set_start_day/:uuid', :to => 'studies#set_start_day'
  #    show
  get 'study/:uuid', :to => 'studies#show', :as => :study
  



  get 'portal/:id', :to => 'ads#go', :as => :portal
  root :to => 'home#welcome'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  before_filter :init
  before_filter :check_profile
  skip_before_filter :verify_authenticity_token, :only => [:add]
  
  def init
    @current_section = 'account'
  end

  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    #session_id = request.session_options[:id]
    session_id = cookies[:cart_id]
    @carts = Cart.where("session_id = ?", session_id)
    if @carts.blank? then
      view = 'noshow'
    else
      view = 'show'
    end
    
    respond_to do |format|
      format.html { render view }# show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  def delete
    Cart.delete(params[:id])

    redirect_to cart_path
    
  end

  # POST /cart/add
  # POST /cart/add.json
  def add
    course = Course.find(params[:id])
    course_id = course.id
    cart_id = cookies[:cart_id]
    puts cookies
    #session_id = cookies[:cart_id].blank? ? request.session_options[:id] : cookies[:cart_id]
    

    # Delete expired carts
    Cart.where("created_at < ?", 72.hour.ago).delete_all
    
    @carts = nil
    # If guest
    if current_user.nil?
      uid = -1
    else # Registered user
      uid = current_user.id
      @carts = Cart.where("user_id = ?", uid).update_all(:session_id => cart_id)
    end

    # Check if the course already in cart
    last_cart = Cart.find_by_session_id(cart_id)
    order_number = ""
    if last_cart.blank? # New cart
      order_number = Time.now.strftime("%Y%m%d%H%M%S") + cart_id.to_i.to_s[0..2]
    else
      if last_cart.order_number.blank?
        order_number = Time.now.strftime("%Y%m%d%H%M%S") + cart_id.to_i.to_s[0..2]
      else
        order_number = last_cart.order_number
      end
    end

    @carts = Cart.where("session_id = ? AND course_id = ?", cart_id, course_id)
    if @carts.first.nil?
      @cart = Cart.new
      @cart.user_id = uid
      @cart.session_id = cart_id
      @cart.course_id = course_id
      @cart.order_number = order_number
      @cart.save
    end
    #render json: @carts, status: :created 
    respond_to do |format|
        format.html { render :action => "index" }
        format.json { render json: @carts, status: :created }
    end
  end

end # end of class

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br />
    <%= f.text_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br />
    <%= f.text_field :order_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th>User</th>
    <th>Course</th>
    <th>Order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= cart.user_id %></td>
    <td><%= cart.course_id %></td>
    <td><%= cart.order_id %></td>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/noshow.html.erb
<dl class="dl-horizontal">
  <dt><%= t('姓名') %></dt>
  <% unless current_user.nil? %>
  <dd><%= current_user.user_profile.lastname %> <%= current_user.user_profile.firstname %></dd>
  <% end %>
  <dt><%= t('會員編號') %></dt>
  <% unless current_user.nil? %>
  <dd><%= current_user.serial_id %></dd>
  <% end %>
</dl>
<hr>

<div class="alert">
  <p class="text-center">
  <strong>購物車內沒有任何課程，要不要去<%= link_to "選購", courses_path %>一下呢？</strong>
  </p>
</div>

<hr class="clearfix">

app/views/carts/show.html.erb
<dl class="dl-horizontal">
  <dt><%= t('姓名') %></dt>
  <% unless current_user.nil? %>
  <dd><%= current_user.fullname %></dd>
  <% else %>
  <dd>尚未登入</dd>
  <% end %>
  <dt><%= t('會員編號') %></dt>
  <% unless current_user.nil? %>
  <dd><%= current_user.serial_id %></dd>
  <% else %>
  <dd>尚未登入</dd>
  <% end %>
</dl>
<hr>
<div>
<table class="table table-striped">
  <tr>
    <th><%= t('課程分類') %></th>
    <th><%= t('課程名稱') %></th>
    <th><%= t('單元數') %></th>
    <th><%= t('課程編號') %></th>
    <th><%= t('上課時間長度') %></th>
    <th><%= t('售價') %></th>
    <th></th>
  </tr>
  <%
  total_price = 0
  @carts.each do |cart|
    %>
    <tr>
      <td><%= cart.course.category.title %></td>
      <td><%= cart.course.title %></td>
      <td><%= cart.course.unit %></td>
      <td><%= cart.course.serial %></td>
      <td><%= cart.course.duration_days %> <%= t('天') %></td>
      <td><%= number_to_currency(cart.course.price, :precision => 0, :locale => :zh_tw) %></td>
      <td>
        <%= link_to delete_cart_path(cart), :title => '刪除', :class => 'btn btn-mini btn-danger', :data => {:method => 'delete'} do %>
          <i class="icon-trash"></i> 刪除
          <% end %>
      </td>
    </tr>
    <%
    total_price += cart.course.price
  end
  %>
  <tr>
    <td colspan="4"><%= t('購物單金額') %></td>
    <td><%= t('小計') %></td>
    <td><%= number_to_currency(total_price, :precision => 0, :locale => :zh_tw) %></td>
    <td></td>
  </tr>
</table>
<div class="clearfix"></div>
<%= link_to "送出訂單", new_user_order_path(@carts.first.order_number), :class => "btn btn-primary pull-right clearfix", :data => {:method => "post", :disable_with => "..."} %>
<div class="clearfix"></div>

</div>
<hr class="clearfix">
<div class="alert clearfix" style="overflow:auto">
  <%= @config[:pay_instruction].html_safe %>
</div>