config/routes.rb
Drwho::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user_registrations", :sessions => "user_sessions" }    
  
  get "inbox", :to => 'inbox#index', :as => :inbox
  get "inbox/:inbox_id", :to => 'inbox#show', :as => :inbox_show
  put "inbox/read/:id", :to => 'inbox#read', :as => :inbox_read
  #delete "inbox/delete/:id", :to => 'inbox#delete'

  get "news/:id", :to => 'news#show', :as => :news_item
  get "news/title/:title", :to => 'news#show_by_title', :as => :news_item_by_title
  get "news", :to => 'news#index', :as => :news_index
  get "my_account", :to => 'my_account#profile', :as => :my_account
  get "my_account/profile"
  get "my_account/cart"
  get "my_account/receipt"
  get "my_account/choose_start_day"
  get "my_account/study_record"
  get "my_account/self_learning"
  get "my_account/news"
  get "my_account/logout"
  get "my_account/calendar", :to => 'my_account#calendar'

  get 'pages/:key', :to => 'pages#show', :as => :page

  get 'profile', :to => 'user_profiles#show', :as => :user_profiles
  get 'profile', :to => 'user_profiles#show', :as => :user_profile
  get 'profile', :to => 'user_profiles#show', :as => :profile
  patch 'profile', :to => 'user_profiles#update'
  get 'profile/edit', :to => 'user_profiles#edit', :as => :edit_user_profile
  

  post 'cart/add/:id(.:format)', :to => 'carts#add', :as => :add_to_cart
  delete 'cart/:id', :to => 'carts#delete', :as => :delete_cart
  get 'cart', :to => 'carts#show', :as => :cart


  get 'order/new/:order_number', :to => 'user_orders#new', :as => :new_user_order
  post 'order/new/:order_number', :to => 'user_orders#new'
  get 'orders', :to => 'user_orders#index', :as => :user_orders
  get 'order/:order_number', :to => 'user_orders#show', :as => :user_order
  resources :user_orders, :only => [:index, :show, :new]
  resources :courses, :only => [:index, :show]

  # SelfLearnings
  get 'study/self_learnings', :to => 'self_learnings#index', :as => :self_learnings
  post 'study/self_learnings', :to => 'self_learnings#create'
  get 'study/self_learning/new', :to => 'self_learnings#new', :as => :self_learning_new
  get 'study/self_learning/:grouping_id', :to => 'self_learnings#show', :as => :self_learning
  patch 'study/self_learning/:grouping_id', :to => 'self_learnings#update'
  delete 'study/self_learning/:grouping_id', :to => 'self_learnings#destroy'
  get 'study/self_learning/:grouping_id/exam', :to => 'self_learnings#exam', :as => :self_learning_exam
  post 'study/self_learning/:grouping_id/exam', :to => 'self_learnings#exam_result'
  get 'study/self_learning/:grouping_id/edit', :to => 'self_learnings#edit', :as => :self_learning_edit


  # Records
  get 'study/records', :to => 'studies#all_records', :as => :study_all_records
  get 'study/records/:uuid', :to => 'studies#record', :as => :study_records  
  get 'study/wrongs/', :to => 'study_records#wrongs', :as => :wrongs
  get 'study/wrongs/course/', :to => 'study_records#wrongs_by_course', :as => :wrongs_by_course
  get 'study/wrongs/course/:uuid', :to => 'study_records#wrongs_in_course', :as => :wrongs_in_course
  get 'study/hardests/:uuid(/course/:course_id)', :to => 'studies#hardests', :as => :study_hardests

  # studies
  get 'study', :to => 'studies#index', :as => :studies
  #    exam
  get 'study/exam/:uuid/day/:day/phase/:phase', :to => 'studies#exam', :as => :study_exam
  post 'study/exam/:uuid/day/:day/phase/:phase', :to => 'studies#exam_submit'
  #    practice
  get 'study/exam/result/:uuid', :to => 'studies#exam_result', :as => :study_exam_result
  get 'study/practice/:uuid/day/:day/phase/:phase', :to => 'studies#practice', :as => :study_practice
  post 'study/practice/:uuid/day/:day/phase/:phase', :to => 'studies#practice_submit'  
  get 'study/practice/result/:uuid', :to => 'studies#practice_result', :as => :study_practice_result
  #    read
  get 'study/read/:uuid/day/:day', :to => 'studies#read', :as => :study_read
  #    set start day
  get "study/set_start_day", :to => 'studies#set_start_day', :as => :set_start_day
  patch 'study/set_start_day/:uuid', :to => 'studies#set_start_day'
  #    show
  get 'study/:uuid', :to => 'studies#show', :as => :study
  



  get 'portal/:id', :to => 'ads#go', :as => :portal
  root :to => 'home#welcome'

end

app/views/common/_flash_message.html.erb
<div class="flash-message">
  <% unless flash[:error].blank? %>
    <p class="alert alert-error"><%= flash[:error] %></p>
  <% end %>
  <% unless flash[:notice].blank? %>
    <p class="alert alert-success"><%= flash[:notice] %></p>
  <% end %>
</div>

app/views/common/_header.html.erb
<header>
    <div class="row">
      <span class="span5">
        <a href="/"><h1 class="site_title"><%= image_tag "/images/logo.jpg", height: "50", class: "logo" %><%= @config[:sitename]%></h1></a>
      </span>
      <span class="span7">
        <% unless @ads[:top_1].nil? %>
        <div class="banner pull-right banner-top half-banner" id="banner-top1"><%= @ads[:top_1].link_tag %></div>
        <% end %>
        <% unless @ads[:top_2].nil? %>
        <div class="banner pull-right banner-top half-banner" id="banner-top2"><%= @ads[:top_2].link_tag %></div>
        <% end %>
        
      </span>
    </div>
    <div id="user-panel" class="">
      <% if user_signed_in? %>
      <%=t('歡迎！')%> <%= current_user.email %>
      <% else %>
      <%= link_to t("登入"), new_user_session_path %> /
      <%= link_to t("註冊"), new_user_registration_path %>
      <% end %>
      <span class="label label-info"><%= link_to t("新訊息") + ' ' + @new_messages.to_s, inbox_path %></span>
      <a class="btn btn-small" href="<%= cart_path %>"><i class="icon-shopping-cart"></i> 購物車</a>
      <% if user_signed_in? %>
      <%= link_to t("登出"), destroy_user_session_path, class: "btn btn-small" %>
      <% end %>
    </div>
  </header>

app/views/common/_login.html.erb
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true, :style => 'max-width:100%' %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password, :style => 'max-width:100%' %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  <div><%= f.submit "登入" %></div>
<% end %>

<%= render "devise/shared/links" %>

app/views/common/_main_nav.html.erb
  <ul class="nav nav-pills">
    <li class="<%= 'active' if controller.controller_name == 'home' %>"><%= link_to t("首頁"), '/' %></li>
    <li class="<%= 'active' if controller.controller_name == 'news' %>"><%= link_to "重要訊息", news_index_path %></li>
    <li class="<%= 'active' if controller.controller_name == 'courses' %>"><%= link_to "課程清單", courses_path %></li>
    <li class="<%= 'active' if @current_section == 'pages_one_on_one' %>"><%= link_to "一對一課程", "/pages/one_on_one" %></li>
    <li class="<%= 'active' if @current_section == 'pages_faq' %>"><%= link_to "常見問答 (FAQ)", "/pages/faq" %></li>
    <li class="<%= 'active' if @current_section == 'pages_contact_us' %>"><%= link_to "聯絡我們", "/pages/contact_us" %></li>

    <% if user_signed_in? %>
    <li class="<%= 'active' if @current_section == 'studies' %>"><%= link_to "上課去", studies_path, :style => 'color:red;' %></li>
    <li class="dropdown <%= 'active' if @current_section == 'account' %>">
      <%= link_to "#", :class => "dropdown-toggle", :data => {:toggle => "dropdown"} do %>
        我的帳戶<b class="caret"></b>
      <% end %>
      <ul class="dropdown-menu">
        <!-- links -->
        <li class="block-1"><%= link_to "購物車", cart_path %></li>
        <li class="block-1"><%= link_to "歷史訂單", user_orders_path %></li>
        <li class="block-1"><%= link_to "選開課日", set_start_day_path %></li>
        <li class="divider"></li>
        <li class="nav-header">易錯排行榜</li>
        <li class="block-2"><%= link_to "全部課程易錯排行榜", wrongs_path %></li>
        <li class="block-2"><%= link_to "單一課程易錯排行榜", wrongs_by_course_path %></li>
        <li class="divider"></li>
        <li class="block-2"><%= link_to "學習記錄", study_all_records_path %></li>
        <li class="block-3"><%= link_to "自我學習", study_self_learnings_path %></li>
        <li class="divider"></li> 
        <li class="block-4"><%= link_to "個人訊息", inbox_path %></li>
        <li class="block-4"><%= link_to "個人資料", profile_path %></li>
        
      </ul>
    </li>
    <% end %>

  </ul>